fix: replace koanf v1.5 with koanf v2
This is needed to get rid of the error message when building collector:

```console
Error: failed to update go.mod: exit status 1. Output:
go: found github.com/SumoLogic/sumologic-otel-collector/pkg/configprovider/globprovider in github.com/SumoLogic/sumologic-otel-collector/pkg/configprovider/globprovider v0.0.0-00010101000000-000000000000
github.com/SumoLogic/sumologic-otel-collector imports
        go.opentelemetry.io/collector/confmap imports
        github.com/knadh/koanf/maps: ambiguous import: found package github.com/knadh/koanf/maps in multiple modules:
        github.com/knadh/koanf v1.5.0 (/home/andrzej/go/pkg/mod/github.com/knadh/koanf@v1.5.0/maps)
        github.com/knadh/koanf/maps v0.1.1 (/home/andrzej/go/pkg/mod/github.com/knadh/koanf/maps@v0.1.1)
github.com/SumoLogic/sumologic-otel-collector imports
        go.opentelemetry.io/collector/confmap imports
        github.com/knadh/koanf/providers/confmap: ambiguous import: found package github.com/knadh/koanf/providers/confmap in multiple modules:
        github.com/knadh/koanf v1.5.0 (/home/andrzej/go/pkg/mod/github.com/knadh/koanf@v1.5.0/providers/confmap)
        github.com/knadh/koanf/providers/confmap v0.1.0 (/home/andrzej/go/pkg/mod/github.com/knadh/koanf/providers/confmap@v0.1.0)
```